# -*- coding: utf-8 -*-
"""API_cotaçao_moeda.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gTJbAY4BfJgH0COPLuxWay_LS-mY9xqk
"""

# api pública 
# cotação de moedas
#json é uma ferramenta importante para trocar informações de sites, em forma de dict
import requests 
import json
# as informações são atualizadas a cada 30 segundos
cotacoes= requests.get('https://economia.awesomeapi.com.br/last/USD-BRL,EUR-BRL,BTC-BRL')
cotacoes= cotacoes.json()
#bid é o valor da cotação 
cotacao_dolar = cotacoes['USDBRL'] ['bid']
#print(cotacoes)
print(cotacao_dolar)

pip install requests